ALTER TABLE public.users 
  ADD COLUMN IF NOT EXISTS unlocked_titles TEXT[] NOT NULL DEFAULT ARRAY['Wanderer']::text[],
  ADD COLUMN IF NOT EXISTS total_maze_steps INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_maze_time INTEGER NOT NULL DEFAULT 0;